<?xml version="1.0"?>
  <robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="bot" params="prefix parent name *origin">

    <xacro:include filename="$(find niryo_one_description)/urdf/niryo_one_gripper.urdf.xacro"/>
    <xacro:gripper prefix="${prefix}"/>
    

    <xacro:property name="distance_origin_shoulder_z" value="0.103" />
    <xacro:property name="distance_shoulder_arm_z" value="0.080" />
    <xacro:property name="distance_arm_elbow_x" value="0.210" />
    <xacro:property name="distance_arm_elbow_y" value="0.0" />
    <xacro:property name="distance_elbow_forearm_x" value="0.0415" />
    <xacro:property name="distance_elbow_forearm_y" value="0.030" />
    <xacro:property name="distance_forearm_wrist_z" value="0.180" />
    <xacro:property name="distance_wrist_hand_x" value="0.0164" />
    <xacro:property name="distance_wrist_hand_y" value="-0.0055" />
    <xacro:property name="distance_hand_tool" value="0.0073" />
	
	<xacro:property name="PI" value="3.14159265359" />

    <xacro:property name="limit_low_shoulder_rotation" value="-3.05433" />
    <xacro:property name="limit_up_shoulder_rotation" value="3.05433" />
    <xacro:property name="limit_low_arm_rotation" value="-1.57080" />
    <xacro:property name="limit_up_arm_rotation" value="0.640187" />
    <xacro:property name="limit_low_elbow_rotation" value="-1.397485" />
    <xacro:property name="limit_up_elbow_rotation" value="${PI/2}" />
    <xacro:property name="limit_low_forearm_rotation" value="-3.05433" />
    <xacro:property name="limit_up_forearm_rotation" value="3.05433" />
    <xacro:property name="limit_low_wrist_rotation" value="-1.74533" />
    <xacro:property name="limit_up_wrist_rotation" value="1.91986" />
    <xacro:property name="limit_low_hand_rotation" value="-2.57436" />
    <xacro:property name="limit_up_hand_rotation" value="2.57436" />

  <xacro:macro name="SimpleTransmissionPosition" params="joint n">
    <transmission name="${prefix}_transmission_${n}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_motor_${n}">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
  

  <!-- Transmission 1 -->
  <xacro:SimpleTransmissionPosition n="1" joint="${prefix}_joint_1" />

  <!-- Transmission 2 -->
  <xacro:SimpleTransmissionPosition n="2" joint="${prefix}_joint_2" />

  <!-- Transmission 3 -->
  <xacro:SimpleTransmissionPosition n="3" joint="${prefix}_joint_3" />

  <!-- Transmission 4 -->
  <xacro:SimpleTransmissionPosition n="4" joint="${prefix}_joint_4" />

  <!-- Transmission 5 -->
  <xacro:SimpleTransmissionPosition n="5" joint="${prefix}_joint_5" />

  <!-- Transmission 6 -->
  <xacro:SimpleTransmissionPosition n="6" joint="${prefix}_joint_6" />



	<!-- Links -->


    <link name="${prefix}_base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/base_link.dae" />
			</geometry>
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/base_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_elbow_forearm_x / 2} ${distance_elbow_forearm_y / 2} 0" rpy="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
        </inertial>
	</link>

    <link name="${prefix}_shoulder_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/shoulder_link.dae" />
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/shoulder_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_elbow_forearm_x / 2} ${distance_elbow_forearm_y / 2} 0" rpy="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
        </inertial>
	</link>

    <link name="${prefix}_arm_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/arm_link.dae" />
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/arm_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_elbow_forearm_x / 2} ${distance_elbow_forearm_y / 2} 0" rpy="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
        </inertial>
	</link>
	
    <link name="${prefix}_elbow_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/elbow_link.dae" /> 
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/elbow_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_elbow_forearm_x / 2} ${distance_elbow_forearm_y / 2} 0" rpy="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
        </inertial>
	</link>

    <link name="${prefix}_forearm_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/forearm_link.dae" />
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/forearm_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_forearm_wrist_z / 2}" rpy="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
        </inertial>
	</link>

    <link name="${prefix}_wrist_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/wrist_link.dae" />
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/wrist_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_wrist_hand_x / 2} ${distance_wrist_hand_y / 2} 0" rpy="0 0 0"/>
            <mass value="0.15"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
	</link>
	
    <link name="${prefix}_hand_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/collada/hand_link.dae" />
			</geometry>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v2/stl/hand_link.stl" />
            </geometry> 
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_hand_tool / 2}" rpy="0 0 0"/>
            <mass value="0.05"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
	</link>
	
    <link name="${prefix}_tool_link"/>

	<!--Joints -->

    <joint name="${prefix}_joint_world" type="fixed">
        <parent link="${parent}" />
        <child link="${prefix}_base_link" />
        <xacro:insert_block name="origin" />
    </joint>

	<joint name="${prefix}_joint_1" type="revolute">
        <parent link="${prefix}_base_link" />
        <child link="${prefix}_shoulder_link" />
		<origin xyz="0 0 ${distance_origin_shoulder_z}" rpy="0 0 0" />
		<axis xyz="0 0 1" />
		<limit effort="1" velocity="1.0" lower="${limit_low_shoulder_rotation}" upper="${limit_up_shoulder_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
	</joint>

	<joint name="${prefix}_joint_2" type="revolute">
        <parent link="${prefix}_shoulder_link" />
        <child link="${prefix}_arm_link" />
        <origin xyz="0 0 ${distance_shoulder_arm_z}" rpy="${PI/2} ${-PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_arm_rotation}" upper="${limit_up_arm_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
		<axis xyz="0 0 1" />
	</joint>

	<joint name="${prefix}_joint_3" type="revolute">
        <parent link="${prefix}_arm_link" />
        <child link="${prefix}_elbow_link" />
        <origin xyz="${distance_arm_elbow_x} ${distance_arm_elbow_y} 0" rpy="0 0 ${-PI/2}" />
		<limit effort="1" velocity="1.0" lower="${limit_low_elbow_rotation}" upper="${limit_up_elbow_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
		<axis xyz="0 0 1" />	
	</joint>

	<joint name="${prefix}_joint_4" type="revolute">
        <parent link="${prefix}_elbow_link" />
        <child link="${prefix}_forearm_link" />
        <origin xyz="${distance_elbow_forearm_x} ${distance_elbow_forearm_y} 0" rpy="0 ${PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_forearm_rotation}" upper="${limit_up_forearm_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
		<axis xyz="0 0 1" />
	</joint>

	<joint name="${prefix}_joint_5" type="revolute">
        <parent link="${prefix}_forearm_link" />
        <child link="${prefix}_wrist_link" />
		<origin xyz="0 0 ${distance_forearm_wrist_z}" rpy="0 ${-PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_wrist_rotation}" upper="${limit_up_wrist_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
		<axis xyz="0 0 1" />
	</joint>

	<joint name="${prefix}_joint_6" type="revolute">
        <parent link="${prefix}_wrist_link" />
        <child link="${prefix}_hand_link" />
        <origin xyz="${distance_wrist_hand_x} ${distance_wrist_hand_y} 0" rpy="0 ${PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_hand_rotation}" upper="${limit_up_hand_rotation}" />
        <dynamics damping="0.1" friction="0.0"/>
		<axis xyz="0 0 1" />
	</joint>

	<joint name="${prefix}_hand_tool_joint" type="fixed">
        <parent link="${prefix}_hand_link" />
        <child link="${prefix}_tool_link" />
        <origin xyz="0 0 ${distance_hand_tool}" rpy="${-PI/2} ${-PI/2} 0" />
	</joint>

    <ros2_control name="${name}" type="system">
      <hardware>
        <plugin>niryo_one_driver/NiryoOneHardwareInterface</plugin>
      </hardware>
      <joint name="${prefix}_joint_1">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}_joint_2">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
        <joint name="${prefix}_joint_3">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
        <joint name="${prefix}_joint_4">
        <command_interface name="position"/>

        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
        <joint name="${prefix}_joint_5">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
        <joint name="${prefix}_joint_6">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
    </ros2_control>
  </xacro:macro>
  </robot>